#!/usr/bin/env bash
# checks if file exists and gives information about it
fn="./school"
if [ -e "$fn" ]; then
	echo "school file exists"
	if [ -s "$fn" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$fn" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi